//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pt_legitymacjestudenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obecnosc
    {
        public int Id_Obecnosci { get; set; }
        public int Indeks { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string notatka { get; set; }
        public int Id_Zajec_pojedynczych { get; set; }
        public Nullable<bool> Spoznienie { get; set; }
    
        public virtual Zajecia_pojedyncze Zajecia_pojedyncze { get; set; }
        public virtual Student Student { get; set; }
    }
}
