//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pt_legitymacjestudenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sala()
        {
            this.Zajecia = new HashSet<Zajecia>();
        }
    
        public int Id_Sali { get; set; }
        public string Budynek { get; set; }
        public string Numer { get; set; }
        public virtual Sala sala { get; set; }
        public string DisplayName
        {
            get
            {
                return sala.Numer + "-" + sala.Budynek;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zajecia> Zajecia { get; set; }
    }
}
