//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pt_legitymacjestudenckie
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheConjuring_dbEntities1 : DbContext
    {
        public TheConjuring_dbEntities1()
            : base("name=TheConjuring_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Obecnosc> Obecnosc { get; set; }
        public virtual DbSet<Przedmiot> Przedmiot { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Wykladowca> Wykladowca { get; set; }
        public virtual DbSet<Zajecia> Zajecia { get; set; }
    }
}
