//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pt_legitymacjestudenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wykladowca
    {
        public int Id_Wykladowcy { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Login_uz { get; set; }
        public string Haslo { get; set; }
    }
}
