//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pt_legitymacjestudenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia_pojedyncze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zajecia_pojedyncze()
        {
            this.Obecnosc = new HashSet<Obecnosc>();
        }
    
        public int Id_Zajec_pojedynczych { get; set; }
        public int Id_Zajec { get; set; }
        public System.DateTime Data_zajec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obecnosc> Obecnosc { get; set; }
        public virtual Zajecia Zajecia { get; set; }
    }
}
