//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pt_legitymacjestudenckie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zajecia()
        {
            this.Obecnosc = new HashSet<Obecnosc>();
        }
    
        public int Id_Zajec { get; set; }
        public int Id_Przedmiotu { get; set; }
        public int Id_Sali { get; set; }
        public Nullable<System.DateTime> Czas { get; set; }
        public Nullable<bool> Tydzien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obecnosc> Obecnosc { get; set; }
        public virtual Przedmiot Przedmiot { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
